### ISSUE TITLE
Attn with Ulysses and LinearZero3

### ISSUE THREAD

**Issue by GeneZC** [feifeibear/Odysseus-Transformer#18]
I have observed that Ulysses is very fast with FSDP yet is memory-inefficient. And you have claimed it may be due to the inefficient memory management of FSDP. 

So I am wondering whether would it be beneficial to enhance attn layer with ulysses and linearzero3 instead of tp+sp?

**Comment by feifeibear** [comment]
First, you statement is not right. Ulysses+FSDP is inefficient I mean. 
FSDP is a block-box provided by pytorch. A self-implemented linearzero3 will be helpful.

**Comment by GeneZC** [comment]
I see.
